/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'rishi' at '18/3/16 1:32 AM' with Gradle 2.5
 *
 * @author rishi, @date 18/3/16 1:32 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
